public class accountList  {     
  /* public static void status(List<Account>accloop){
        for(Account acc: accloop){
        if(acc.Status__c=='Active'){
            (acc.Industry='Agriculture');
        }
           List<contact> contacts=new  List<contact>();
                contact c=new contact();
                c.FirstName='s';
                c.LastName='Apex';
                c.AccountId=acc.Id;
                  contacts.add(c);
            
            contact Con=new contact();
               Con.FirstName='T';
               Con.LastName='Apex';
                Con.AccountId=acc.Id;
                  contacts.add(Con);
                
                if(!contacts.IsEmpty()){
                     insert contacts;
            }
    } 
        }*/
    }