/**
* @File Name : bookListViewButton.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : July 10, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | July 10, 2025 |   | Initial Version
**/

public class bookListViewButton {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}