public class condition {
    public static void Myclass(){
         Integer month = 2;
    
    if(month >=1 && month <=4){
        system.debug('This is Winter');
        }
    else if(month >=4 && month <=8){
        system.debug('This is summer');
        }
         else if(month >=8 && month <=12){
        system.debug('This is rainy');
        } else {
        system.debug('This is not');
        } 
    }
    
   
}